build-prod-image-api-bo:
  extends:
    - .prod
    - .build_image

# Deploy
deploy-prod-api-bo-sha:
  only:
    changes:
      - "app/*"
      - "app/**/*"
  extends:
    - .deploy-prod
    - .deploy-sha

deploy-prod-api-bo-latest:
  except:
    changes:
      - "app/*"
      - "app/**/*"
  extends:
    - .deploy-prod
    - .deploy-latest
